### PR TITLE
Fix #274 (omni-compiler): Do not output varDecl from external module in interfaceDecl 

### PR DESCRIPTION
**Pull request by clementval**
Fix omni-compiler/omni-compiler#274

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval It looks this PR doesn't work as intended because of some PRs that have been merged.

**Comment by clementval** [comment]
Ok, I’ll have a look

**Comment by clementval** [comment]
@h-murai I think it works as intended. The `varDecl` are not produced. `id` are still there. If they should also be omitted, I can do it as well. 

The resulting code is the following: 
```fortran
MODULE mod1
 INTERFACE
  SUBROUTINE gcl_addfieldtohaloexchange_wrapper ( ) BIND(C , NAME = "communicationwrapper_add_field_to_halo_exchange" )
   USE , INTRINSIC :: iso_c_binding

  END SUBROUTINE gcl_addfieldtohaloexchange_wrapper
 END INTERFACE
END MODULE mod1
```
And this matches with the original one.

**Comment by h-murai** [comment]
@clementval Sorry. I've misunderstood. It's ok that `id`s are there.

**Pull request merged**
