### PR TITLE
Fix #72: Output correctly PUBLIC/PRIVATE statement for OPERATOR

### LINKED ISSUE #72: PUBLIC :: OPERATOR(.eq.) becomes  PUBLIC :: .eq. and does not compile
The following code reproduce the error

```fortran
module mtime_datetime
  implicit none
  private
  public :: min, max
  public :: assignment(=)
  public :: operator(>)
  public :: operator(<)
  public :: operator(<=)
  public :: operator(>=)
  public :: operator(==)
  public :: operator(/=)

  interface min
  end interface min
  
  interface max
  end interface max
  
  interface assignment (=)
  end interface assignment (=)
  
  interface operator (>)
  end interface operator (>)
  
  interface operator (<)
  end interface operator (<)
  
  interface operator (<=)
  end interface operator (<=)
  
  interface operator (>=)
  end interface operator (>=)
  
  interface operator (==)
  end interface operator (==)
  
  interface operator (/=)
  end interface operator (/=)
end module mtime_datetime

module mtime_timedelta
  use mtime_datetime
  implicit none
  private

  public :: operator(+)
  public :: operator(-)
  public :: operator(*)
  public :: operator(>)
  public :: operator(<)
  public :: operator(<=)
  public :: operator(>=)
  public :: operator(==)
  public :: operator(/=)
   
  interface operator (+)
  end interface operator (+)
  
  interface operator (-)
  end interface operator (-)
  
  interface operator (*)
  end interface operator (*)
  
  interface operator (>)
  end interface operator (>)
  
  interface operator (<)
  end interface operator (<)
  
  interface operator (<=)
  end interface operator (<=)
  
  interface operator (>=)
  end interface operator (>=)
  
  interface operator (==)
  end interface operator (==)
  
  interface operator (/=)
  end interface operator (/=)
  
end module mtime_timedelta
```

Not compilable code
```fortran
MODULE mtime_datetime
 PUBLIC :: min
 PUBLIC :: max
 PUBLIC :: ASSIGNMENT(=)
 PUBLIC :: OPERATOR(.gt.)
 PUBLIC :: OPERATOR(.lt.)
 PUBLIC :: OPERATOR(.le.)
 PUBLIC :: OPERATOR(.ge.)
 PUBLIC :: OPERATOR(.eq.)
 PUBLIC :: OPERATOR(.ne.)
END MODULE mtime_datetime

MODULE mtime_timedelta
 USE mtime_datetime
 PUBLIC :: OPERATOR(+)
 PUBLIC :: OPERATOR(-)
 PUBLIC :: OPERATOR(*)
 PUBLIC :: .le.
 PUBLIC :: .eq.
 PUBLIC :: .ge.
 PUBLIC :: .gt.
 PUBLIC :: .lt.
 PUBLIC :: .ne.
END MODULE mtime_timedelta
```

### PR DESCRIPTION
**Pull request by clementval**
In some case, the PUBLIC statement was output like `PUBLIC :: .eq.` which is not compilable. 

No output is `PUBLIC :: OPERATOR(.eq.)`

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval It looks to me that the existing master branch outputs a right code like `PUBLIC :: OPERATOR(.eq.)` and this PR makes no changes for the test code.

**Comment by clementval** [comment]
@h-murai Might be a consequence of another open PR. I'll do the test...

**Comment by clementval** [comment]
@h-murai I have actually found a case where this happens in the current master. I'll set up a minimal test case and submit it as an issue to link with this PR

**Comment by clementval** [comment]
@h-murai I have added a code reproducing the error. #72

**Pull request merged**
