### PR TITLE
Fix #59: Apply workaround to have compilable code with gfortran-7 

### LINKED ISSUE #59: Derived type cannot be declared with both PRIVATE and BIND(C) with gfortran
The following code is compilable with gfortran but not anymore once passed through the front-end and back-end. 
```fortran
MODULE mod1
  IMPLICIT NONE
  PRIVATE

  TYPE, BIND(c) :: t_rt
    INTEGER :: i
  END TYPE t_rt
END MODULE mod1
```

```fortran
MODULE mod1
 TYPE , PRIVATE , BIND( C ) :: t_rt
 END TYPE t_rt
END MODULE mod1
```

```bash
  TYPE , PRIVATE , BIND( C ) :: t_rt
                                   1
Error: Derived type 't_rt' at (1) cannot be declared with both PRIVATE and BIND(C) attributes
```

This is specified in the Fortran standard at R427

### PR DESCRIPTION
**Pull request by clementval**
Fix for #59

### CODE REVIEW

**Comment by clementval** [comment]
@h-murai Looks like it's even worse than I thought. Even the following code is not accepted by gfortran. 

```fortran 
MODULE mod1
 INTEGER , PRIVATE :: pi
 PRIVATE :: t_rt
 TYPE , BIND( C ) :: t_rt
  INTEGER :: i
 END TYPE t_rt
END MODULE mod1
```

Only a global `PRIVATE` would work. But I don't think this is good for a fix.
```fortran 
MODULE mod1
 PRIVATE
 INTEGER , PRIVATE :: pi
 TYPE , BIND( C ) :: t_rt
  INTEGER :: i
 END TYPE t_rt
END MODULE mod1
```

**Comment by clementval** [comment]
@h-murai I found the exact code in gfortran that is issuing the error. 

```c
 /* Make sure we don't have conflicts with the attributes.  */
 if (derived_sym->attr.access == ACCESS_PRIVATE)
   {
     gfc_error ("Derived type '%s' at %L cannot be declared with both "
                "PRIVATE and BIND(C) attributes", derived_sym->name,
                &(derived_sym->declared_at));
     retval = FAILURE;
   }
```

So it looks like this is really intentional. I would suggest to apply a work around to just lower the access specifier to `PUBLIC` or none for such type as a temporary solution. We could even issue a warning if such case is triggered.

**Comment by h-murai** [comment]
@clementval I think it's better to issue the warning.

**Comment by clementval** [comment]
@h-murai I added the warning.

**Pull request merged**
