### PR TITLE
Fix #83: Allow identical generic-name for interface block

### LINKED ISSUE #83: Generic interface block sharing generic-name
If two or more generic interfaces that are accessible in a scoping unit have the same local name, they are interpreted as a single generic interface. This is not the case currently as the following example will trigger an error.

```fortran
MODULE issue83
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: p_gatherv
       
  INTERFACE p_gatherv
    MODULE PROCEDURE p_gatherv_int
  END INTERFACE

CONTAINS
  SUBROUTINE p_gatherv_int()
  END SUBROUTINE p_gatherv_int
END MODULE issue83
```

```fortran
MODULE mod1
  USE issue83, ONLY: p_gatherv
  IMPLICIT NONE
  PRIVATE

  INTERFACE p_gatherv
    MODULE PROCEDURE p_gatherv_1d
  END INTERFACE p_gatherv

CONTAINS
  SUBROUTINE p_gatherv_1d()
  END SUBROUTINE p_gatherv_1d
END MODULE mod1
```

```bash
line 6: 'p_gatherv' is already defined as a generic procedure in module ''
```

### PR DESCRIPTION
**Pull request by clementval**
#83

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval With this PR, the following wrong code is erroneously accepted without any messages.

```fortran
MODULE issue83
  integer :: p_gatherv
END MODULE issue83
```
```fortran
MODULE mod1
  USE issue83

  INTERFACE p_gatherv
    MODULE PROCEDURE p_gatherv_1d
  END INTERFACE p_gatherv

CONTAINS
  SUBROUTINE p_gatherv_1d()
  END SUBROUTINE p_gatherv_1d
END MODULE mod1
```

**Comment by clementval** [comment]
@h-murai Ok, I'll fix this problem

**Comment by clementval** [comment]
@h-murai This should work like this. Or maybe there is a bug in the import module? I mean the imported subs should maybe flagged as generic... What do you think?

**Comment by h-murai** [comment]
@clementval I mean this is a wrong code, and gfortran actually detects errors as follows but F_Front with this PR doesn't.

```
$ gfortran -c foo.f90
foo.f90:7:21:

   INTERFACE p_gatherv
                     1
Error: VARIABLE attribute of ‘p_gatherv’ conflicts with PROCEDURE attribute at (1)
foo.f90:8:20:

     MODULE PROCEDURE p_gatherv_1d
                    1
Error: MODULE PROCEDURE at (1) must be in a generic module interface
foo.f90:9:5:

   END INTERFACE p_gatherv
     1
Error: Expecting END MODULE statement at (1)
```

**Comment by clementval** [comment]
@h-murai Yes, I updated the fix to not accept this code. But I was wondering if the initial problem was not coming from the import module. Because this should be true `IS_GENERIC_PROCEDURE_TYPE(ID_TYPE((iid)))` normally but it's not.

**Comment by h-murai** [comment]
@clementval There may be something wrong about importing generic.

I found the following code in `F-input-xmod.c` but it looks to me that this never works.

```c
    } else if (strncmp(rtid, "V", 1) == 0) {
        TYPE_DESC tp = getTypeDesc(ht, rtid);
        TYPE_BASIC_TYPE(ftp) = TYPE_GENERIC;
        FUNCTION_TYPE_SET_GENERIC(ftp);
```

**Comment by clementval** [comment]
@h-murai I’ll have a deeper look

**Comment by clementval** [comment]
I close this PR and will reopen one with a proper fix

**Pull request closed without merging**
