### PR TITLE
Fix #133: do not reduce if kind is not available

### LINKED ISSUE #133: Reduced parameter leads to wrong code (linked with #99)
This is issue can be linked with #99 

The following code will lead to not compilable transformed code after `F_Front` and `F_Back` processings.

```fortran
MODULE mo_kind
  IMPLICIT NONE
  PRIVATE
  INTEGER, PARAMETER :: pd =  12
  INTEGER, PARAMETER :: rd = 307
  INTEGER, PARAMETER :: dp = SELECTED_REAL_KIND(pd,rd)
  INTEGER, PARAMETER :: wp = dp

  PUBLIC :: wp
END MODULE mo_kind
```

```fortran
MODULE mo_physical_constants
  USE mo_kind, ONLY: wp
  IMPLICIT NONE
  PUBLIC
  REAL(wp), PARAMETER :: rdaylen=86400._wp
END MODULE mo_physical_constants
```

```fortran
MODULE mo_cuparameters

  USE mo_kind,       ONLY: jprb=>wp
  USE mo_physical_constants, ONLY: rday => rdaylen

CONTAINS
  ELEMENTAL FUNCTION rteta(ptime)
    REAL(KIND=jprb)             :: rteta
    REAL(KIND=jprb), INTENT(in) :: ptime
    rteta = ptime/(rday*365.25_JPRB)
  END FUNCTION rteta
END MODULE mo_cuparameters
```

```fortran
MODULE mo_cuparameters
 USE mo_kind , ONLY: jprb => wp
 USE mo_physical_constants , ONLY: rday => rdaylen

CONTAINS
 ELEMENTAL FUNCTION rteta ( ptime )
  REAL ( KIND= selected_real_kind ( 12 , 307 ) ) :: rteta
  REAL ( KIND= selected_real_kind ( 12 , 307 ) ) , INTENT(IN) :: ptime

  rteta = ptime / ( 86400._wp * 365.25_jprb )
 END FUNCTION rteta

END MODULE mo_cuparameters
```

In the above code, `wp` is not available. 

The error `gfortran-7` will produce:
```bash
mod3.f90:10:29:

   rteta = ptime / ( 86400._wp * 365.25_jprb )
                             1
Error: Missing kind-parameter at (1)
```

@h-murai There is two solution to this problem. 
1) Having the option to not to parameter reduction like said on #99 
2) Detecting these cases in the front-end and avoid reducing when kind parameter is not available. 

I think 2 make more sense. What do you think @h-murai

### PR DESCRIPTION
**Pull request by clementval**
Fix #133

### CODE REVIEW

**Comment by clementval** [comment]
@h-murai Do you think we should check if the kind identifier is available in the current scope or like the current status of this pull request, we just abort reduction when external parameter have kind.

**Comment by h-murai** [comment]
@clementval I think that, of course, it's better to check it. But it has a low priority because a right translation can be done with this PR.

**Comment by clementval** [comment]
@h-murai Agreed! So if it’s fine with you, can you merge this PR if there is no change required of course

**Comment by h-murai** [comment]
@clementval Sorry, I changed my opinion a little. It should be checked for some obvious cases (e.g. the kind parameter is a constant).

**Comment by clementval** [comment]
@h-murai I updated the code to reduce kind if it's a constant

**Pull request merged**
