### PR TITLE
Fix #570, #575 & #563 (omni-compiler): Fix for Derived-type mismatch + import multi ids

### PR DESCRIPTION
**Pull request by clementval**
Fix omni-compiler/omni-compiler#563, omni-compiler/omni-compiler#570 & omni-compiler/omni-compiler#575

@h-murai I have to introduce a new attribute in the `.xmod` file to track the original type id (`imported_id`). This is needed because in some cases a type can be imported twice with indirection in some other module and therefore will not have the same address but will still be the same type. With the original type id, we can control this information.

### CODE REVIEW

**Comment by clementval** [comment]
#65 should be merged at the same time to have a consistent fix.

**Comment by clementval** [comment]
@h-murai `issue63.f90` is still failing. I'll fix that by tomorrow and let you know when everything is fine.

**Comment by clementval** [comment]
@h-murai The fix is now fine ...

**Comment by clementval** [comment]
@h-murai Do you think you can review this PR anytime soon? Would be great to have it as this is the last one to hav a full ICON parsing.

**Comment by h-murai** [comment]
@clementval Ok. I'll try to do it as soon as possible.

**Comment by clementval** [comment]
@h-murai No rush! Thanks a lot!

**Comment by h-murai** [comment]
@clementval I merged this PR. Could you update the XcodeML/Fortran specification to include the new attribute `imported_id`?

**Comment by clementval** [comment]
@h-murai Ok, I'll make a PR to edit the spec

**Pull request merged**
