### PR TITLE
Add exceptions to c++ build

### PR DESCRIPTION
**Pull request by FrostyMike**
Should be applied after https://github.com/omni-compiler/xcodeml-tools/pull/177

### CODE REVIEW

**Comment by clementval** [comment]
@FrostyMike Which commit are are new in this PR? It's hard to review as is because it includes commits from another PR.

**Comment by FrostyMike** [comment]
> @FrostyMike Which commit are are new in this PR? It's hard to review as is because it includes commits from another PR.

There is only one commit:

https://github.com/omni-compiler/xcodeml-tools/pull/175/commits/6965f9bdf90fd45b14f75eb844423f4447c437ab

**Review by h-murai — APPROVED** [review]

**Comment by h-murai** [comment]
@clementval LGTM. Can we merge this?

**Review by clementval — APPROVED** [review]
@h-murai Ok for me if it's ok on your side.

**Pull request merged**
