### PR TITLE
General performance improvements for parsing process (#104 and #129)

### PR DESCRIPTION
**Pull request by clementval**
* Use `khash` hash table implementation to speed up the deep copy (#129)
* Use `khash` set to speed up type_link_add operation (#104)

### CODE REVIEW

**Comment by clementval** [comment]
Contains fix for #131 as well

**Comment by clementval** [comment]
@h-murai I can give you some performance number on this PR tomorrow.

**Comment by clementval** [comment]
This pull request reduce the time for `compile_USE_decl` from several minutes (I stopped after 15 minutes without being finished) to 3 seconds. So a minimal speedup of 300x!

**Comment by clementval** [comment]
@h-murai I also did some changes in the output module process. This greatly reduces the processing time from over 20min to 5 seconds. 

On one file in ICON, this PR reduce to process time from 114 minutes to ~15 seconds. An improvement of 400x in term of speedup.

**Comment by h-murai** [comment]
@clementval Excellent work!  I'll review and merge it.

**Comment by h-murai** [comment]
@clementval I found some warnings that can be actually ignored, as follows. Please check to be sure that they are ok.

```
F-output-xcodeml.c:4248:12: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return ret;
```

**Comment by clementval** [comment]
@h-murai I've reviews the warnings. Should be ok now.

**Pull request merged**
