### PR TITLE
Proposition to use clang-format to have an homogenous style across all files

### PR DESCRIPTION
**Pull request by clementval**
In order to have a common code style across all files, I wanted to propose to use `clang-format` that can format the code according to a `.clang-format` file. 
This PR is an example of what the code can look like when `clang-format` is applied. 
What do you think? @mnakao @h-murai 

I added a target `format` in the Makefile

```bash
$ make format # apply the clang-format on all .c and .h files
```

### CODE REVIEW

**Comment by h-murai** [comment]
@clementval I think we can use it. We'll discuss about this with other developers. Please wait for a decision for a while.

**Comment by clementval** [comment]
@h-murai Thanks, no rush it's just a proposition ...

**Comment by h-murai** [comment]
@clementval After discussing about this, we basically agreed about it. So, is it the actual operation that we ask developers to run `make format` before they commit files?

**Comment by clementval** [comment]
@h-murai Exactly, we should do it once to have a first commit with all files formatted according to the `.clang-format` rules and then the goal is that developers just run `make format` before issuing a PR. 

Of course, the rules in the `.clang-format` can be adapted to what you guys things is the best formatting that you like.

**Comment by clementval** [comment]
@h-murai I can prepare an initial commit with the formatting like this one ... this one is already obsolete and has conflicts. 
Btw, it would be better to merge other open PR before that otherwise it will generate so many conflicts.

**Comment by clementval** [comment]
New PR in #107

**Pull request closed without merging**
