### PR TITLE
Fix #136: Allow COMPLEX*8 and COMPLEX*16 to be used as fct return value

### LINKED ISSUE #16: Argument keywords of Intrinsic Procedures
should be supported.

### LINKED ISSUE #136: COMPLEX*16 cannot be defined as function return value
Following code is not working properly with the current `F_Front`
```fortran
module mod1 
contains

complex*16 function fct1()
end function
end module mod1
```

```bash
"test2.f90:mod1", line 5: only function/subroutine statement are allowed in contains top level
"test2.f90:mod1", line 5: syntax error
"test2.f90:mod1", line 9: declaration among executables
```

### PR DESCRIPTION
**Pull request by clementval**
Fix #16

### CODE REVIEW

**Comment by clementval** [comment]
@h-murai Can you have a look at this? Thanks.

**Comment by h-murai** [comment]
@clementval With this PR, `real*8` and `integer*8` for function type cannot be accepted. Since `get_keyword_optional_blank` is for processing Fortran keywords like `end if` or `end function`, I think there should be a better way to resolve the issue. I'm sorry that I have no idea for it now.

**Comment by clementval** [comment]
@h-murai Ok, I had another idea before doing this ... so I'll try to implement it.

**Comment by clementval** [comment]
I close this PR for now and I will re-open one when I have a different solution

**Pull request closed without merging**
