### PR TITLE
Fix bug with type bound procedures with lt, le, gt, and ge operator n…

### PR DESCRIPTION
**Pull request by m214089**
This PR fixes the problems described in issue #160 

Fix is simply XML escaping the respective name. This was missing for type bound procedures.

### CODE REVIEW

**Review by clementval — APPROVED** [review]
lgtm

**Comment by clementval** [comment]
@m214089 Did you try to read a `.xmod` file generated with this new version. If you have a small test case it would be nice to add it to testate. `F-FrontEnd/test/testdata`

**Comment by m214089** [comment]
@clementval Ok, I will make a small test.

**Comment by m214089** [comment]
@clementval Ok, I have added a small test which does work.

**Comment by clementval** [comment]
@m214089 Good. I can merge once the CI is green ... looks like it is stuck for the moment.

**Comment by clementval** [comment]
@h-murai @mnakao The CI seems to be stuck. Maybe this is due to this problem. 

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

Can someone with repository settings access try the fix?

**Comment by mnakao** [comment]
Sorry for my late reply.

I tried to solve this issue, but without success.
It's a good time to change your role in this repository to admin.
Is it possible for you to solve this issue?

**Comment by clementval** [comment]
@mnakao I'll try to fix it.

**Comment by clementval** [comment]
@m214089 The fix is merged
@mnakao Seems the CI is back working. Thanks!

**Pull request merged**
